name: Update WakaTime Stats

on:
  schedule:
    - cron: '0 0 * * *' # Har kuni soat 00:00 da ishga tushadi
  workflow_dispatch: # Qo'lda ishga tushirish uchun

jobs:
  update-waka:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update WakaTime Stats
        uses: waka-time/readme@v1
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
